name: habits_tracker
description: A habits tracking app 

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1  # For Windows file operations
  flutter_local_notifications: ^16.3.2  # For habit reminders
  timezone: ^0.9.2  # For scheduling notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true